version: '3.9'

services:
  db:
    image: postgres:17
    container_name: coveragex-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: coveragex
    ports:
      - "6543:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - coveragex-network

  backend:
    build:
      context: ./backend
    container_name: coveragex-backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/coveragex"
    depends_on:
      - db
    networks:
      - coveragex-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000/api" # pass to Docker build
    container_name: coveragex-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - coveragex-network

volumes:
  db-data:

networks:
  coveragex-network:
    driver: bridge
