FROM node:20-bullseye

WORKDIR /app

# Copy dependency files first
COPY package*.json ./

# Install dependencies
RUN npm config set registry https://registry.npmmirror.com
RUN npm install

# Copy rest of the code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 5000

# Use CMD to wait for DB and run migrations at runtime
CMD ["sh", "-c", "npx prisma db push && npm run dev"]
